### ISSUE TITLE
nuget references

### ISSUE THREAD

**Issue by Pinox** [microsoft/WinUI-3-Demos#2]
where are the nuget packages coming from ?  they don't get pulled in my solution.

**Comment by marb2000** [comment]
WinUI comes from nuget.org. 
For .NET 5, you can find the feed here (down in the page):
https://github.com/dotnet/installer

**Comment by Pinox** [comment]
@marb2000 

Not following you.  I followed the instructions and these are my references.

Do I need to install something else ?  

![winui3](https://user-images.githubusercontent.com/5297255/82663217-88c18000-9c2f-11ea-91bf-7f0dd5acde5a.png)

**Comment by Pinox** [comment]
thanks @marb2000 .   I think there is an issue with VS preview. After  creating new templates from WinUI for desktop , then only did my references start updating.  very weird behavior. Took me like 15minutes getting this project to update.
