### ISSUE TITLE
DemoBuildCs Crashes After “Select Folder” Clicked

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/WinUI-3-Demos#3]
### Bug
I have followed the README instructions, built the code, and ran the application (Debug x64). However, once I click “Select Folder” in the file picker, the application crashes.

**Note**: I have tried to select on different folders locally with the same result. Also, I was able to get the DemoBuildCpp to run and work!

### Error Message
AsyncCausalityTracer : System.InvalidCastException: Unable to cast object of type 'WinRT.IInspectable' to type 'Windows.Foundation.Diagnostics.IAsyncCausalityTracerStatics'.
   at System.Threading.Tasks.AsyncCausalityTracer..cctor()
The thread 0x17494 has exited with code 0 (0x0).
Exception thrown at 0x00007FFC8017C330 (coreclr.dll) in DemoBuildCs.exe: 0xC0000005: Access violation reading location 0x0000000000000010.
The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.

### **Version Info**
**NuGet package version:** 
My installed packages are 
[Microsoft.VCRTForwarders.140 v1.0.6]
[Microsoft.WinUI 3.0.0-preview1.200515.3]

**Windows version:** Version 1809 (OS Build 17763.1158)
**Device**: Desktop

**Comment by FelixGirard** [comment]
I also had this error. 

If I debug in native only it doesn't crash.

**Comment by jaytri37** [comment]
I am having same issue.
I also tried native only but it didin't work.

**Comment by marb2000** [comment]
I can't repro this so closing the bug.
